# Generated by Django 5.0.1 on 2024-01-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prisoner_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisoner',
            name='uuid',
        ),
    ]
