# Generated by Django 5.0.1 on 2024-01-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prisoner_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='prisoners',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='prisoner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prisoner', to='main.prisoner'),
        ),
    ]
