# Generated by Django 5.0.1 on 2024-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_lawyer_prisoners_lawyer_prisoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='gender',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
