# Generated by Django 5.0.1 on 2024-02-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_prisoner_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='fir',
        ),
        migrations.DeleteModel(
            name='FIR',
        ),
    ]
