# Generated by Django 5.0.1 on 2024-02-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_crime_fir_delete_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_of_registration', models.DateField()),
                ('ps_id_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='fir',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fir', to='main.fir'),
        ),
    ]
