# Generated by Django 5.0.1 on 2024-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_prisoner_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
